[project]
name = "english-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bedrock-agentcore>=0.1.5",
    "bedrock-agentcore-starter-toolkit>=0.1.14",
    "langchain>=0.3.27",
    "langchain-aws>=0.2.33",
    "langgraph>=0.6.8",
    "pip>=25.2",
    "boto3>=1.35.0",
    "pyyaml>=6.0",
    "strands-agents>=1.20.0",
    "strands-agents-tools>=0.2.18",
    "mcp-proxy-for-aws>=1.1.2",
]
